name: php-app

x-db-info: &ENV
  # password for root (admin) account
  MYSQL_ROOT_PASSWORD: root_password
  # default database name
  # idk if changing this replaces the old db or what
  MYSQL_DATABASE: db
  # default non admin username
  MYSQL_USER: user
  # default non admin password
  MYSQL_PASSWORD: password


services:
  main:
    build: .
    volumes:
      - ..:/app
    links:
      - db
      - admin

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      <<: *ENV

  admin:
    image: phpmyadmin
    restart: always
    environment:
      <<: *ENV

volumes:
  mysql:
